version: '3.8'

services:
  java-runner:
    build:
      context: ./docker
      dockerfile: Dockerfile.java
    container_name: code-runner-java
    volumes:
      - ./docker:/app
    tty: true
    stdin_open: true
    command: tail -f /dev/null

  python-runner:
    build:
      context: ./docker
      dockerfile: Dockerfile.python
    container_name: code-runner-python
    volumes:
      - ./docker:/app
    tty: true
    stdin_open: true
    command: tail -f /dev/null

  javascript-runner:
    build:
      context: ./docker
      dockerfile: Dockerfile.javascript
    container_name: code-runner-javascript
    volumes:
      - ./docker:/app
    tty: true
    stdin_open: true
    command: tail -f /dev/null

  cpp-runner:
    build:
      context: ./docker
      dockerfile: Dockerfile.cpp
    container_name: code-runner-cpp
    volumes:
      - ./docker:/app
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    working_dir: /tmp/workspace
